### ISSUE TITLE
MYDUMPER hung up when MYSQL got net_write_timeout

### ISSUE THREAD

**Issue by vnlo77250** [maxbube/mydumper#162] opened 2018-10-19 08:42 UTC
When MYSQL issue net_write_timeout (60 seconds), but MYDUMPER does not detect it and continue doing nothing forever, and have to be killed manually.

2018-10-19T00:43:22.164987Z 109135 [Note] Connection 109135 avortée vers la bd: 'unconnected' utilisateur: 'myhost' hôte: '0.0.0.0' (Timeout d'écriture des paquets envoyés)

**Comment by vnlo77250** [comment] 2021-04-01 10:51
Sorry, i don't, this issue is quite random and i can't reproduce it at will.
I believe that mydumper thread does not detect that the connection is lost and there is no idle timeout, so mydumper hang up.

**Comment by davidducos** [comment] 2021-07-16 18:08
I'm closing as I'm not able to reproduce. If you found a workaround, please let use know.

**Closed by davidducos** 2021-07-16 18:08 UTC
Labels: help wanted, invalid
