### ISSUE TITLE
Mydumper abort on slave because it falsely detect long query

### ISSUE THREAD

**Issue by vnlo77250** [maxbube/mydumper#278] opened 2020-12-22 22:03 UTC
Mydumper abort with the error "There are queries in PROCESSLIST running longer than 60s, aborting dump".
The only long query running is the slave thread running with "system user":

1. Connect:  Waiting for master to send event
2. Query:     Slave has read all relay log; waiting for more updates

Mydumper should bypass query of sytem user.

**Comment by fredricj** [comment] 2020-12-23 09:29
Duplicate of #236

**Closed** 2021-02-05 16:26 UTC
Labels: duplicate
