### ISSUE TITLE
[enhancement] Multi-threaded tables creation

### ISSUE THREAD

**Issue by vnlo77250** [maxbube/mydumper#311] opened 2021-04-13 06:15 UTC
Myloader does not use multi-threading to create tables, resulting to a really slow restoration (13,5 hours for about a million tables).
It's the same problem for views, triggers, routines and events.

**Comment by davidducos** [comment] 2021-04-13 11:40
This is a duplicate of https://github.com/maxbube/mydumper/issues/311

**Closed** 2021-09-03 12:24 UTC
Labels: duplicate
