### ISSUE TITLE
Error switching to database  whilst restoring table

### ISSUE THREAD

**Issue by khywolf** [maxbube/mydumper#37] opened 2017-02-07 09:13 UTC
mydumper:
mydumper -u root -S /tmp/mysql.sock -p xxxx --regex '^(?!(mysql|information_schema|test))' -o /usr/local/backup/xxxx --less-locking

myloader:
myloader -d /usr/local/backup/xxxx -u root -p xxxx -S /tmp/mysql.sock.3310 -o

error:
** (myloader:7648): CRITICAL **: Error switching to database  whilst restoring table xxxx

What causes?

**Comment by checco** [comment] 2017-03-20 10:25
Same problem here.

I found a blog post where they say to change the `wait_timeout` variable into a biggest value. But this fix doesn't worked for me, because on RDS I have already a `wait_timeout` well configured. I'm trying to restore a very large database with a very large number of rows without success.

**Comment by keithyzk** [comment] 2017-07-12 09:19
Same problem here.

**Comment by keithyzk** [comment] 2017-07-12 09:20
I still did not find a solution. It makes me feel very annoying, I have spent a lot of time on the top of the

**Comment by maxbube** [comment] 2017-08-30 17:42
Can someone post a case that I can reproduce?

**Comment by kehh** [comment] 2017-08-30 23:47
I managed to stop this happening yesterday by matching max_packet_size between the source and the destination.

**Comment by maxbube** [comment] 2017-11-03 20:53
Hi @kehh good to know and thanks for the update!

**Comment by flobee** [comment] 2018-04-07 20:03
one or both of 
#ulimit -n 10000
#myloader --threads 1 
solves it for me BUT: without root access to the db server to improve setup/config this was my only chance

**Comment by egorsmorgunov** [comment] 2020-09-02 07:38
> Can someone post a case that I can reproduce?

`  [root@moodle /mnt]$ mydumper -u root -p pass -B atutor`
`  [root@moodle /mnt]$ myloader -u root -p pass  -B moodle2020 --directory=/mnt/export-20200902-101354 -o`
** Message: 4 threads created
** Message: Creating database `moodle2020`
** Message: Dropping table or view (if exists) `moodle2020`.`AC_lang_base`
** Message: Creating table `moodle2020`.`AC_lang_base`

** (myloader:27008): CRITICAL **: Error switching to database moodle2020 whilst restoring table AC_lang_base
** Message: Thread 1 shutting down
** Message: Thread 4 shutting down
** Message: Thread 2 restoring `moodle2020`.`AC_lang_base` part 0
** Message: Thread 3 shutting down

even if
`[root@moodle /mnt/export-20200902-101354]$ `rename 's/atutor/moodle2020/g' *.sql``

and in moodle2020-schema-create.sql **replace**
**CREATE DATABASE `atutor`**
on
**CREATE DATABASE `moodle2020`**
we get an error "Error switching to database ..."

**Comment by egorsmorgunov** [comment] 2020-09-02 07:54
I solved it. **If the name of your new base is different from the name of the previous base**

1.1 Try to `drop database moodle2020;`
1.2. `myloader -u root -p pass  -B moodle2020 -d /mnt/export-20200902-104419`

**Comment by dongjiashun** [comment] 2020-10-15 05:46
这次全库备份，恢复，就会报错， 只会创建表结构，没法导入数据。 单表备份恢复就没这个问题，大坑啊

**Comment by mugurelmargaritkurtgeiger** [comment] 2021-02-02 16:53
I'm experiencing the same issue trying to restore the database from a host running Amazon Linux 2, using the latest mydumper/myloader version. Here's the error I am getting:

** (myloader:22457): CRITICAL **: 16:45:30.457: Error switching to database dbname whilst restoring table apple

** (myloader:22457): CRITICAL **: 16:45:30.457: Error switching to database dbname whilst restoring table cucumber

** (myloader:22457): CRITICAL **: 16:45:30.457: Error switching to database dbname whilst restoring table orange

** (myloader:22457): CRITICAL **: 16:45:30.457: Error switching to database dbname whilst restoring table tomato

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table tangerine

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table banana

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table kiwi

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table pineapple

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table grape

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table watermelon

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table lemon

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table avocado

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table cherry

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table clementine

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table coconut

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table peach

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table pear

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table strawberry

** (myloader:22457): CRITICAL **: 16:45:30.458: Error switching to database dbname whilst restoring table plum

myloader 0.10.1, built against MySQL 5.7.32-35

I have verified:

wait_timeout is big enough
max_allowed_packet is big enough
innodb_buffer_pool_size is big enough
ulimit limits are not hit

I have tried:

using a single thread
downgrading myloader to an older, working version

**Comment by davidducos** [comment] 2021-02-02 18:58
@mugurelmargaritkurtgeiger 

This issue is not the same that the initial. in the error that you are presenting you have the "dbname".
I need this information:
- mydumper and myloader execution command
- ls of the backup directory

Thanks

**Comment by davidducos** [comment] 2021-05-06 18:40
We are closing it as we don't have any feedback
https://github.com/maxbube/mydumper/wiki/Support

**Closed by davidducos** 2021-05-06 18:40 UTC
Labels: incomplete
