### ISSUE TITLE
The database can not be created by myloader if there is no table in it

### ISSUE THREAD

**Issue by wangxj1986** [maxbube/mydumper#201] opened 2019-08-22 10:19 UTC
When I dump the data from mysql using mydumper, all databases can be dumped rightly including the empty database which have no tables in it, but the empty database can not be created using myloader.
I think the empty database is also useful, why can it not be loaded by myloader?
test version 0.9.1 & 0.9.5

**Comment by wangxj1986** [comment] 2019-08-22 10:24
The schema file of the empty database can also be created, but have no effect on myloader.

**Comment by tsolodov** [comment] 2019-09-06 00:20
duplicate of  #110

**Comment by maxbube** [comment] 2020-04-16 18:10
Closing as duplicate.

**Closed by maxbube** 2020-04-16 18:10 UTC
