### ISSUE TITLE
Error when trying to export table with column named "order"

### ISSUE THREAD

**Issue by diego10arg** [maxbube/mydumper#241] opened 2020-04-17 18:50 UTC
Hi,

I'm running mydumper on MySQL 8.0.16 and when I try to export one particular table with a column named "order" it fails with the following message:

** (mydumper:4289): CRITICAL **: 15:42:43.029: Error dumping table (testdb.test_table) data: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order,ins_user,upd_user,upd_date FROM `testdb`.`test_table' at line 1 

I tried changing the column name to "item_order" and it worked properly, so I believe that is the issue.

To export my database, I am running

` mydumper -u root -a --regex '^((testdb))'`

**Comment by dupondje** [comment] 2020-07-29 09:52
Hi,

Checked this, but normally this should work fine.
Can you paste me the SHOW CREATE TABLE for that table?

And eventually the exact query that is executed (via gdb or query logging)

Thanks

**Comment by fredricj** [comment] 2020-07-29 10:27
I think this is already fixed by #216

**Comment by davidducos** [comment] 2021-01-19 15:48
@diego10arg can you confirm if this issue is still happening with the latest version?

**Comment by davidducos** [comment] 2021-03-31 17:48
I have checked this and the issue is not happening anymore

**Closed by davidducos** 2021-03-31 17:48 UTC
Labels: help wanted, incomplete
